name: GitHub Actions Deploy Backend To Vercel Prod
env:
  VERCEL_ORG_ID: team_TWDZ1JndJoHz45LEG2t7tjuY
  VERCEL_PROJECT_ID: prj_NHux2xyamm2vf8Ra7jGF5o8Ky0LO

on:
  workflow_call:

jobs:
  deploy-prod-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=6Pe840Mz3IjN3q7odiFnjKi3
      - name: Build Project Artifacts
        run: vercel build --prod --token=6Pe840Mz3IjN3q7odiFnjKi3
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=6Pe840Mz3IjN3q7odiFnjKi3
