name: GitHub Actions Deploy Frontend To Vercel Prod
env:
  VERCEL_ORG_ID: team_TWDZ1JndJoHz45LEG2t7tjuY
  VERCEL_PROJECT_ID: prj_VUjEOUvox9qkNJOfyvbWQejM6dy7

on:
  workflow_call:

jobs:
  deploy-prod-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
