name: GitHub Actions Deploy Production

on:
  push:
    branches: ["main"]

jobs:
  deploy-prod-backend:
    uses: ./deploy-backend-vercel-prod.yml

  deploy-prod-frontend:
    needs: deploy-prod-backend
    uses: ./deploy-frontend-vercel-prod.yml
